inherit_from: .rubocop_todo.yml
AllCops:
  TargetRubyVersion: 2.3

Style/Documentation:
  Enabled: false

# it is ok to write 'string' and "string"
Style/StringLiterals:
  Enabled: false

# 'class ActionDispatch::IntegrationTest' in single line, no need two lines
Style/ClassAndModuleChildren:
  Enabled: false

# tasks for setup data could be very long
Metrics/BlockLength:
  Exclude:
    - 'test/**/*'
    - 'lib/**/*'

# big test big ABC size
Metrics/AbcSize:
  Exclude:
    - 'test/**/*'

# I like to put comma after each line
Style/TrailingCommaInLiteral:
  Enabled: false
# also in arguments
Style/TrailingCommaInArguments:
  Enabled: false

# I like methods in 10 lines but some are bigger
Metrics/MethodLength:
  Max: 20
  Exclude:
    - 'test/**/*'
    - 'lib/**/*'

# I use double quotes in all places
Style/StringLiteralsInInterpolation:
  Enabled: false

# do not need to write # frozen_string_literal: true
Style/FrozenStringLiteralComment:
  Enabled: false
