inherit_from: .rubocop_todo.yml
AllCops:
  TargetRubyVersion: 2.3

# it is OK that code explains instead class documentation
Style/Documentation:
  Enabled: false

# 'class ActionDispatch::IntegrationTest' in single line, no need two lines
Style/ClassAndModuleChildren:
  Enabled: false

# tasks for setup data could be very long
Metrics/BlockLength:
  Exclude:
    - 'test/**/*'
    - 'lib/**/*'

# big test big ABC size
Metrics/AbcSize:
  Max: 25
  Exclude:
    - 'test/**/*'

# line length is not important everywhere
Metrics/LineLength:
  Exclude:
    - "db/**/*"

# I like to put comma after each line
Style/TrailingCommaInLiteral:
  Enabled: false
# also in arguments
Style/TrailingCommaInArguments:
  Enabled: false

# I like methods in 10 lines but some are bigger
Metrics/MethodLength:
  Max: 20
  Exclude:
    - 'test/**/*'
    - 'lib/**/*'

# do not need to write # frozen_string_literal: true
Style/FrozenStringLiteralComment:
  Enabled: false

# I use double quotes in all places
#Style/StringLiteralsInInterpolation:
#  Enabled: false

