shared:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] || '123asd' %>

  # Neo4j
  neo4j_type: <%= ENV["NEO4J_TYPE"] %>
  neo4j_host: <%= ENV["NEO4J_HOST"] %>
  neo4j_port: <%= ENV["NEO4J_PORT"] %>
  neo4j_bolt_port: <%= ENV["NEO4J_BOLT_PORT"] %>
  neo4j_username: <%= ENV["NEO4J_USERNAME"] %>
  neo4j_password: <%= ENV["NEO4J_PASSWORD"] %>

  # sending emails
  smtp_username: <%= ENV["SMTP_USERNAME"] %>
  smtp_password: <%= ENV["SMTP_PASSWORD"] %>
  # default_url is required for links in email body or in links in controller
  # when url host is not available (for example rails console)
  default_url:
    host: <%= ENV["DEFAULT_URL_HOST"] || (Rails.env.production? ? "www.premesti.se" : "localhost") %>
    port: <%= ENV["DEFAULT_URL_PORT"] || (Rails.env.development? ? Rack::Server.new.options[:Port] : nil) %>
  mailer_sender: <%= ENV["MAILER_SENDER"] || "Premesti.se <ajd@premesti.se>" %>
  # leave this empty if you do not want to enable server error notifications
  # othervise comma separated emails
  exception_recipients: <%= ENV["EXCEPTION_RECIPIENTS"] %>

  # Facebook Autentication
  facebook_app_id: <%= ENV['FACEBOOK_APP_ID'] %>
  facebook_key: <%= ENV["FACEBOOK_KEY"] %>
  facebook_secret: <%= ENV["FACEBOOK_SECRET"] %>
  facebook_page_url: https://www.facebook.com/premesti.se
  # Google signup
  google_client_id: <%= ENV["GOOGLE_CLIENT_ID"] %>
  google_client_secret: <%= ENV["GOOGLE_CLIENT_SECRET"] %>

  # for maps
  google_api_key: <%= ENV["GOOGLE_API_KEY"] %>

  # REDIS_URL is used for cache store, sidekiq and action cable

test:
  neo4j_type: <%= ENV["NEO4J_TEST_TYPE"] %>
  neo4j_host: <%= ENV["NEO4J_TEST_HOST"] %>
  neo4j_port: <%= ENV["NEO4J_TEST_PORT"] %>
  neo4j_bolt_port: <%= ENV["NEO4J_TEST_BOLT_PORT"] %>
  neo4j_username: <%= ENV["NEO4J_TEST_USERNAME"] %>
  neo4j_password: <%= ENV["NEO4J_TEST_PASSWORD"] %>
